web: python manage.py migrate --no-input && gunicorn scholarium_project.wsgi --bind 0.0.0.0:$PORT --timeout 120
release: python manage.py migrate --no-input && python manage.py collectstatic --no-input
