# Generated by Django 4.2.30 on 2026-04-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_mins', models.IntegerField(default=30)),
                ('is_studied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='agent.skillnode')),
            ],
        ),
    ]
