# Generated by Django 4.2.30 on 2026-04-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillnode',
            name='estimated_hours',
            field=models.IntegerField(default=1),
        ),
    ]
