# Generated by Django 4.2.30 on 2026-04-20 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0004_skillnode_estimated_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('activity_type', models.CharField(choices=[('subtopic_complete', 'Subtopic Complete'), ('session_pass', 'Session Pass'), ('goal_complete', 'Goal Complete')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
