# Generated by Django 4.2.30 on 2026-04-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_session_created_at_session_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
