# Generated by Django 4.2.30 on 2026-05-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_subtopic_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='skill_node',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.DeleteModel(
            name='LearningPath',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
