# Generated by Django 4.2.30 on 2026-05-02 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0009_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_subtopics_snapshot', models.JSONField(default=list)),
                ('question_count', models.IntegerField(default=7)),
                ('difficulty', models.CharField(choices=[('easy_medium', 'Easy to Medium')], default='easy_medium', max_length=20)),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('result_summary', models.TextField(blank=True)),
                ('weak_concepts', models.JSONField(default=list)),
                ('revision_priority', models.JSONField(default=list)),
                ('gap_summary', models.TextField(blank=True)),
                ('questions_json', models.JSONField(default=list)),
                ('user_answers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='agent.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_quizzes', models.JSONField(default=list)),
                ('accuracy_over_time', models.JSONField(default=list)),
                ('subtopic_coverage', models.JSONField(default=dict)),
                ('recommendation_insight', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_analytics', to='agent.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'goal')},
            },
        ),
    ]
