# Generated by Django 4.2.30 on 2026-05-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_quizsession_quizanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='skill_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='skillnode',
            name='skill_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
