# Generated by Django 4.2.30 on 2026-04-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_activity_date_user_streak_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_activity_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='streak_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_xp',
        ),
    ]
